name: publish docs
on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup env
        run: pip install sphinx recommonmark pydata_sphinx_theme

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: make html

      - name: Commit to deploy repo
        run: |
          git config --global init.defaultBranch master
          git config --global user.name 'Max'
          git config --global user.email 'mkraev@codio.com'
          git init
          git remote add deploy https://MaximKraev@github.com/codio/knowledge-deploy
          touch .nojekyll
          git add .
          git commit -am "Automated deploy"
          git push -f deploy master
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        working-directory: build
