name: publish docs
on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup env
        run: pip install sphinx recommonmark pydata_sphinx_theme

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: make html

      - name: Upload artifactory
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
          retention-days: 2

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build

      - name: Commit to report
        run: |
          git init
          git config --global user.name 'Max'
          git config --global user.email 'mkraev@codio.com'
          git remote set-url origin https://MaximKraev@github.com/codio/knowledge-deploy
          git commit -am "Automated deploy"
          git push -f
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        working-directory: build
