name: Update search
on:
  schedule:
    - cron:  '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: scrape
        uses: Embraser01/docsearch-scraper-action@master
        args: 
          - run /github/workspace/algolia-config.json
        secrets: 
          - ${{ secrets.API_KEY }}
          - ${{ secrets.APPLICATION_ID }}]
