name: Update search
on:
  schedule:
    - cron:  '0 22 */2 * *'
  push:
    branches:
      - master
jobs:
  algolia_indexer:
    runs-on: ubuntu-latest
    name: Index Algolia
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get Config
      id: config
      run: |
        echo "CONFIG=$(cat algolia-config.json | jq -r tostring)" >> $GITHUB_ENV

    - name: Algolia Docsearch Action
      run: | 
        docker run \
          -e "APPLICATION_ID=${{ secrets.APPLICATION_ID }}" \
          -e "API_KEY=${{ secrets.API_KEY }}" \
          -e "INDEX_NAME=CodioDocs" \
          -e "CONFIG=${{ env.CONFIG }}" \
          algolia/docsearch-scraper
