name: publish docs
on:
  schedule:
    - cron:  '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup env
        uses: "Embraser01/docsearch-scraper-action@master"
        args: ["run /github/workspace/algolia-config.json"]
        secrets: ["API_KEY", "APPLICATION_ID"]
