name: Update search
on:
  schedule:
    - cron:  '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: scrape
        uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_api_key: ${{ secrets.API_KEY }}
          algolia_application_id: ${{ secrets.APPLICATION_ID }}]
          file: algolia-config.json